CXX      = mpic++
CXXFLAGS ?= -std=c++20
CPPFLAGS ?= -fopenmp -O3 -Wall -pedantic -I$(PACS_ROOT)/include -I$(PACS_ROOT)/src/Parallel/MPI/PMAtrix
LDLIBS   ?= 
LINK.o := $(LINK.cc)

EXEC = main
SRCS = $(wildcard *.cpp) 
OBJS = $(SRCS:.cpp=.o) 

DEPEND = make.dep

.PHONY = all $(EXEC) $(OBJS) clean distclean $(DEPEND)

all: $(DEPEND) $(EXEC)

$(EXEC): $(OBJS)

$(OBJS): %.o: %.cpp

clean:
	$(RM) $(DEPEND)
	$(RM) *.o

distclean: clean
	$(RM) $(EXEC)
	$(RM) *.csv *.out *.bak *~

$(DEPEND): $(SRCS)
	@$(RM) $(DEPEND)
	@for file in $(SRCS); \
	do \
	  $(CXX) $(CPPFLAGS) $(CXXFLAGS) -MM $${file} >> $(DEPEND); \
	done

-include $(DEPEND)